# Generated by Django 3.2.9 on 2021-12-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0002_auto_20211214_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulea',
            name='ens',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='module',
            field=models.ManyToManyField(to='Elearning.ModuleA'),
        ),
        migrations.AlterModelTable(
            name='modulea',
            table='ModuleA_tab',
        ),
    ]
