# Generated by Django 3.2.9 on 2021-12-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Elearning', '0003_auto_20211214_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='seanceenligne',
            name='etud',
            field=models.ManyToManyField(to='Elearning.Etudiant'),
        ),
        migrations.AddField(
            model_name='seancepresontiel',
            name='etud',
            field=models.ManyToManyField(to='Elearning.Etudiant'),
        ),
    ]
